language: java

jdk:
  - openjdk14

sudo: false
script:
  - mvn test -B
env:
  global:
    - CODECOV_TOKEN="00a07545-1b30-46d6-8d27-a7830cc5ec4e"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -free_person@inbox.ru
    on_success: never # default: change
    on_failure: always # default: always